steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "wally-backend"
      - "--image"
      - "gcr.io/bulk-games-wally/wally-backend:540e17d56ea228aabe0d94b097ab45f90461b1d5"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--command"
      - "./launch"
      - "--env-vars-file"
      - "env-vars.yaml"
      - "--update-secrets"
      - "WALLY_github_token=WALLY_GITHUB_TOKEN:latest,WALLY_auth=WALLY_ROCKET_AUTH:latest,/secrets/SERVICE_ACCOUNT=WALLY_SERVICE_ACCOUNT:latest"
timeout: 900s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
